vich_uploader:
    db_driver: orm

    mappings:
        produits_image:
           uri_prefix: /produits
           upload_destination: '%kernel.project_dir%/public/produits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        categories_image:
           uri_prefix: /categories
           upload_destination: '%kernel.project_dir%/public/categories'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
