<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE6xJXxw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE6xJXxw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE6xJXxw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE6xJXxw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerE6xJXxw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'E6xJXxw',
    'container.build_id' => '392a7989',
    'container.build_time' => 1586852702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE6xJXxw');
