<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIERJHhr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIERJHhr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIERJHhr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIERJHhr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIERJHhr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IERJHhr',
    'container.build_id' => '25800686',
    'container.build_time' => 1586510074,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIERJHhr');
