<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAAxxYR1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAAxxYR1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAAxxYR1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAAxxYR1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAAxxYR1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AAxxYR1',
    'container.build_id' => '16119632',
    'container.build_time' => 1586354040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAAxxYR1');
